default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  adapter: sqlite3
  database: db/development.sqlite3
  <<: *default

test:
  adapter: sqlite3
  database: db/test.sqlite3
  <<: *default

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    url: <%= ENV["DATABASE_URL"] %>